<?php

namespace Home\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstudioPrimarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstudioPrimarioRepository extends EntityRepository
{
}
