entityName: 'Oficina'
entity: 'Home\BackendBundle\Entity\Oficina'
repository: 'HomeBackendBundle:Oficina'
index: 'admin_oficina'
new: 'admin_oficina_new'
edit: 'admin_oficina_edit'
show: 'admin_oficina_show'
create: 'admin_oficina_create'
update: 'admin_oficina_update'
delete: 'admin_oficina_delete'
sessionFilter: 'OficinaControllerFilter'
fieldsindex:    
    a.id:
        label: 'Id'
        name: 'Id'
        type: 'integer'    
    a.nombre:
        label: 'Nombre'
        name: 'Nombre'
        type: 'string'    
    a.denominacionCorta:
        label: 'Denominacioncorta'
        name: 'Denominacioncorta'
        type: 'string'    
    a.ofiCUE:
        label: 'Oficue'
        name: 'Oficue'
        type: 'integer'    
    a.ofiCUI:
        label: 'Oficui'
        name: 'Oficui'
        type: 'integer'    
    a.jurMarcBaj:
        label: 'Jurmarcbaj'
        name: 'Jurmarcbaj'
        type: 'integer'
    a.jurisdiccion:
        label: 'Jurisdiccion'
        name: 'Jurisdiccion'
        type: 'MANY_TO_ONE'
    a.ambito:
        label: 'Ambito'
        name: 'Ambito'
        type: 'MANY_TO_ONE'
fieldsshow:
    a.id:
        label: 'Id'
        name: 'Id'
        type: 'integer'
    a.nombre:
        label: 'Nombre'
        name: 'Nombre'
        type: 'string'
    a.denominacionCorta:
        label: 'Denominacioncorta'
        name: 'Denominacioncorta'
        type: 'string'
    a.ofiCUE:
        label: 'Oficue'
        name: 'Oficue'
        type: 'integer'
    a.ofiCUI:
        label: 'Oficui'
        name: 'Oficui'
        type: 'integer'
    a.jurMarcBaj:
        label: 'Jurmarcbaj'
        name: 'Jurmarcbaj'
        type: 'integer'
    a.jurisdiccion:
        label: 'Jurisdiccion'
        name: 'Jurisdiccion'
        type: 'MANY_TO_ONE'
    a.concursoxcargos:
        label: 'Concursoxcargos'
        name: 'Concursoxcargos'
        type: 'ONE_TO_MANY'
    a.ambito:
        label: 'Ambito'
        name: 'Ambito'
        type: 'MANY_TO_ONE'